version: '3'
services:
  wordpress:
    image: unosquare/intranet_wp:latest
    ports:
      - 80:80
    depends_on:
      - mariadb
    restart: always
    links:
      - mariadb:mariadb
    environment:
      DB_NAME: 'unoWordpressxn84'
      DB_USER: 'w8w9gAn6SYp0'
      DB_PASSWORD: 'ePyzpUgN8YRS'
      DB_HOST: 'mariadb'
      DB_WP_PREFIX: 'wp_'
      WP_DEBUG: 'false' 
    volumes:
      - wordpress-data:/var/www/html:rw
  mariadb:
    image: unosquare/intranet_db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pwd
      MYSQL_DATABASE: unoWordpressxn84
      MYSQL_USER: w8w9gAn6SYp0
      MYSQL_PASSWORD: ePyzpUgN8YRS
    volumes:
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-data:
  wordpress-data:

# networks:
#  frontend:
#  backend
# docker run --rm -ti mariadb:5.5 mysqldump -h unosquarewordpress.ce9q87nktug9.eu-west-1.rds.amazonaws.com -u w8w9gAn6SYp0 -pePyzpUgN8YRS unoWordpressxn84