version: '3'
services:
  wordpress:
    image: unosquare/intranet_wp:0.0.0
    ports:
      - 8081:80
    environment:
      DB_NAME: 'unoWordpressxn84'
      DB_USER: 'w8w9gAn6SYp0'
      DB_PASSWORD: 'ePyzpUgN8YRS'
      DB_HOST: 'unosquarewordpress.ce9q87nktug9.eu-west-1.rds.amazonaws.com'
      DB_WP_PREFIX: 'wp_'
      WP_DEBUG: false
      # tokens
      AUTH_KEY: '[VDov6_W/mgYAPQ.MABYWzee?Y}C1klu%X_BMgoXT:Yj=BdQ[r*q/%JMT7oGFDz_'
      SECURE_AUTH_KEY: '6}^L8(?4|QR}O5W+Mwh$8te=$3|21u&mW0guLkI{i0fSq^KvtCEu G{SX`/[#3+!'
      LOGGED_IN_KEY: '[[gI3]qLFpxHiC63qSqIPB$j8/d-1[Hh1pcsgRPOVt_t9WtIBe*R?f2I]5j <VWV'
      NONCE_KEY: '[4M,qYVWFi/zdR:=.,w<RanKW!*51&bM`)9~a/(iDj3r_?LBHXIAU8Q*gzY|&fmm'
      AUTH_SALT: '*o%ZC@mmpY23}DTXn9o/m#bIGw,D1Yi8UR7[;2TuQ$80:t$>4T0nB`E6/9{^ ( $'
      SECURE_AUTH_SALT: 'Fh$)7XIr0NAS:y1qVD2jMWTnxs0o1Sm7:___e6/5aOv{?XX80jUKrGPUqS2,b9!#'
      LOGGED_IN_SALT: ']W%I#l8E:%U/RoRSI2(-];H=MhIJ1!`yAijBd!Q%|X=pO_DG5e+|.Z~ d*1?A_,Q'
      NONCE_SALT: 'uON )e$1Ep|L4^ThF4v$#Rbvelc[1opz(P*muh;Vg9CdGL#BlZGbAC9@M}<n%B]c'

  mariadb:
    image: unosquare/extranetdb:0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root-pwd
      MYSQL_DATABASE: unoWordpressxn84
      MYSQL_USER: w8w9gAn6SYp0
      MYSQL_PASSWORD: ePyzpUgN8YRS

volumes:
  mariadb-data:
  wordpress-data:

# docker run --rm -ti mariadb:5.5 mysqldump -h unosquarewordpress.ce9q87nktug9.eu-west-1.rds.amazonaws.com -u w8w9gAn6SYp0 -pePyzpUgN8YRS unoWordpressxn84